{
  "hash": "64ebd64728e96b40abec4f1042bb5174",
  "result": {
    "engine": "knitr",
    "markdown": "---\nbibliography: references.bib\n---\n\n\n\n\n# Introduction to parsnip and brms {#sec-intro_parsnip_brms}\n\nThe statistical modeling tools we use play a pivotal role in how efficiently and effectively we can model our research data. Here, we will use two powerful R tools, `parsnip` and `brms` to work seamlessly with statistical modeling.\nBoth tools support theoretically motivated modeling and robust parameter estimation, making them ideal for the complex and often noisy datasets typical of neuroscience.\n\nThe `parsnip` package [@parsnip] is part of the tidymodels ecosystem [@kuhn2020], designed to unify the process of model specification, fitting, and prediction. This package is valuable for its simplicity and flexibility. In principle, researchers can define models without committing to a specific computational engine at the outset. For instance, a linear regression model can be fitted using a variety of methods, such as lm or glmnet for penalized regression. This allow us to experiment with diverse algorithms without having to rewrite the underlying model code.\n\nTo explore how these packages work, let's start by simulating a dataset:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gt)\n\nset.seed(123)  # For reproducibility\nn <- 100  # Number of observations\n\n# We define parameters\nbeta_0 <- 20   # Baseline marker intensity\nbeta_1 <- 15   # Effect of treatment in dose\nsigma <- 5     # Standard deviation of noise\n\n# Generate data\ntreatment_dose <- rep(0:2, length.out = n)  # 3 dose levels\nmarker_intensity <- beta_0 + beta_1 * treatment_dose + rnorm(n, mean = 0, sd = sigma)\n\n# Create data frame\ncell_data <- data.frame(treatment_dose = treatment_dose, marker_intensity = marker_intensity)\n\n# View the first few rows\ngt(head(cell_data))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"typxvkpthc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#typxvkpthc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#typxvkpthc thead, #typxvkpthc tbody, #typxvkpthc tfoot, #typxvkpthc tr, #typxvkpthc td, #typxvkpthc th {\n  border-style: none;\n}\n\n#typxvkpthc p {\n  margin: 0;\n  padding: 0;\n}\n\n#typxvkpthc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#typxvkpthc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#typxvkpthc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#typxvkpthc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#typxvkpthc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#typxvkpthc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#typxvkpthc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#typxvkpthc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#typxvkpthc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#typxvkpthc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#typxvkpthc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#typxvkpthc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#typxvkpthc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#typxvkpthc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#typxvkpthc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#typxvkpthc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#typxvkpthc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#typxvkpthc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#typxvkpthc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#typxvkpthc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#typxvkpthc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#typxvkpthc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#typxvkpthc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#typxvkpthc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#typxvkpthc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#typxvkpthc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#typxvkpthc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#typxvkpthc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#typxvkpthc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#typxvkpthc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#typxvkpthc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#typxvkpthc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#typxvkpthc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#typxvkpthc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#typxvkpthc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#typxvkpthc .gt_left {\n  text-align: left;\n}\n\n#typxvkpthc .gt_center {\n  text-align: center;\n}\n\n#typxvkpthc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#typxvkpthc .gt_font_normal {\n  font-weight: normal;\n}\n\n#typxvkpthc .gt_font_bold {\n  font-weight: bold;\n}\n\n#typxvkpthc .gt_font_italic {\n  font-style: italic;\n}\n\n#typxvkpthc .gt_super {\n  font-size: 65%;\n}\n\n#typxvkpthc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#typxvkpthc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#typxvkpthc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#typxvkpthc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#typxvkpthc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#typxvkpthc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#typxvkpthc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#typxvkpthc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#typxvkpthc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"treatment_dose\">treatment_dose</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"marker_intensity\">marker_intensity</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"treatment_dose\" class=\"gt_row gt_right\">0</td>\n<td headers=\"marker_intensity\" class=\"gt_row gt_right\">17.19762</td></tr>\n    <tr><td headers=\"treatment_dose\" class=\"gt_row gt_right\">1</td>\n<td headers=\"marker_intensity\" class=\"gt_row gt_right\">33.84911</td></tr>\n    <tr><td headers=\"treatment_dose\" class=\"gt_row gt_right\">2</td>\n<td headers=\"marker_intensity\" class=\"gt_row gt_right\">57.79354</td></tr>\n    <tr><td headers=\"treatment_dose\" class=\"gt_row gt_right\">0</td>\n<td headers=\"marker_intensity\" class=\"gt_row gt_right\">20.35254</td></tr>\n    <tr><td headers=\"treatment_dose\" class=\"gt_row gt_right\">1</td>\n<td headers=\"marker_intensity\" class=\"gt_row gt_right\">35.64644</td></tr>\n    <tr><td headers=\"treatment_dose\" class=\"gt_row gt_right\">2</td>\n<td headers=\"marker_intensity\" class=\"gt_row gt_right\">58.57532</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nThis simulated dataset mimics a scenario in basic, cellular neuroscience where a treatment influences the intensity of a marker associated with oxidative stress. We modeled a baseline intensity of 20 units, and stipulated that each unit increase in dose raises the marker intensity by 15 units on average. We then added some noise ($\\sigma = 5$) to account for  biological variability.\n\nNow, let's use `Parsnip` and `brms` to fit a simple linear model and appreciate the machinery of these packages.\n\n::: panel-tabset\n### Parsnip\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(parsnip)\n\nparsnip_model <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(marker_intensity ~ treatment_dose, data = cell_data)\n```\n:::\n\n\n\n\n\n### BRMS\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(brms)\n\nbrms_model <- brm(\n  marker_intensity ~ treatment_dose,\n  data = cell_data,\n  seed = 123,\n  file = \"models/Intro_brms_models_Fit1.rds\",\n  file_refit = \"never\"\n)\n```\n:::\n\n\n\n\n:::\n\n## An overview of parameter interpretation\n\nIn both cases, we fitted the same model (marker_intensity ~ treatment_dose) aiming to investigate the distribution of marker intensity conditioning on the treatment dose. Now, let's see the model results. We need to use a different strategy for both packages:\n\n::: panel-tabset\n### Parsnip\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\n\ntidy(parsnip_model, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term           estimate std.error statistic  p.value conf.low conf.high\n  <chr>             <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)        20.9     0.717      29.2 4.36e-50     19.5      22.3\n2 treatment_dose     14.5     0.558      26.0 8.34e-46     13.4      15.6\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(parsnip_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.874         0.872  4.57      677. 8.34e-46     1  -293.  592.  600.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\n\n\n### BRMS\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(brms)\n\nsummary(brms_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: marker_intensity ~ treatment_dose \n   Data: cell_data (Number of observations: 100) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept         20.92      0.70    19.54    22.32 1.00     3290     2471\ntreatment_dose    14.52      0.55    13.46    15.59 1.00     2951     2596\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     4.62      0.34     4.03     5.31 1.00     3759     3139\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n\n:::\n\nWe can see that the parameters for the `intercept` and the `treatment_dose` are similar for both models. The intercept ( 20.9131) reflects the baseline measurement. Of course, we know this value already because it was one of the parameters we used to do our simulation. This means that the marker intensity is 20.9 when the treatment dose is at its minimum. On the other hand, the parameter for treatment dose indicates us an increase of 14.5. For the `parsnip` model, the 95% confidence intervals are specified in the `conf.low` and `conf.high` columns, whereas for `brms` thew credible intervals are specified under the columns `l-95% CI` and `u-95% CI`. Finally, the `sigma` parameter in a linear regression model (obtained for the `parsnip` model  using `glance`) specifies the residual standard error. This encompasses an estimation of of the standard deviation of the residuals (errors), representing the differences between the observed values and the values predicted by the model. Smaller the sigma, less the distance between the observations (your data) and the values predicted by your model.  \n\nThe interpretation of the parameters is a fundamental aspect of statistical modelling and inference, and we will explore the many nuances of this throughout the book. \n\n## References\n\n::: {#refs}\n:::\n\n\n\n\n\n\n\n",
    "supporting": [
      "Intro_Parsnip-Brms_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}